import assert from 'node:assert/strict'
import test,{before,after,beforeEach} from 'node:test'
import * as db from './test-helpers/dependency-database-fixture.mjs'
const enabled=process.env.RUN_SUPABASE_INTEGRATION==='1',check=(name,fn)=>test(name,{skip:!enabled},fn),q=db.quote
const scalar=sql=>JSON.parse(db.rpc(sql))
const register=()=>scalar(`select public.register_accounting_refresh_connection(${q(db.user)},'xero','tenant-a','tenant-a',(select grant_id::text from public.xero_connections_public where user_id=${q(db.user)} and tenant_id='tenant-a'));`)
const scope=c=>`${q(c.connectionId)},${q(c.ownerId)},${q(c.provider)},${q(c.providerOrganisationId)},${c.epoch}`
const accept=(c,t='opportunistic',key=null)=>scalar(`select public.accept_product_accounting_refresh(${scope(c)},${q(t)},${key?q(key):'null'});`)
const count=()=>db.psql('select count(*) from public.accounting_refresh_jobs;')
const accounting=(interval='30 minutes')=>{const r=db.candidate(),proposal=db.proposalFor(r);const outcome=scalar(`select to_jsonb(p) from public.promote_xero_sync_run_with_promises(${q(r.run)},${q(db.owner)},${r.fence},clock_timestamp()-interval ${q(interval)},${proposal?db.json(proposal):'null'}) p;`);assert.equal(outcome.promoted,true);return r}
const frozen=()=>db.psql(`select jsonb_build_object('billing',(select count(*) from public.billing_usage_days),'raw',(select count(*) from public.xero_raw),'runs',(select count(*) from public.xero_sync_runs),'promises',(select count(*) from public.invoice_promises),'disputes',(select count(*) from public.invoice_disputes),'actions',(select count(*) from public.collection_actions));`)
before(()=>{if(enabled)db.setup()});after(()=>{if(enabled)db.cleanup()});beforeEach(()=>{if(enabled)db.reset()})
check('fresh activity is not_due and creates no job or billing/accounting writes',()=>{accounting('59 minutes');const c=register(),before=frozen();assert.equal(accept(c).outcome,'not_due');assert.equal(count(),'0');assert.equal(frozen(),before)})
check('due activity accepts once; repeated navigation coalesces',async()=>{accounting('60 minutes');const c=register();const results=await Promise.all(Array.from({length:5},()=>db.psqlAsync(`set role service_role;select public.accept_product_accounting_refresh(${scope(c)},'opportunistic');`)));const jobs=results.map(JSON.parse).map(r=>r.job.id);assert.equal(new Set(jobs).size,1);assert.equal(count(),'1')})
check('manual bypasses age threshold but respects publication cooldown',()=>{accounting('30 minutes');const c=register();assert.equal(accept(c,'manual').outcome,'cooldown');db.psql(`update public.xero_sync_tenant_state set last_successful_sync_at=clock_timestamp()-interval '6 minutes' where user_id=${q(db.user)} and tenant_id='tenant-a';`);assert.equal(accept(c,'manual').outcome,'started')})
check('duplicate clicks join; scoped idempotency returns the same job',()=>{const c=register(),a=accept(c,'manual','stable'),b=accept(c,'manual','stable'),d=accept(c,'manual','different');assert.equal(a.job.id,b.job.id);assert.equal(a.job.id,d.job.id);assert.equal(count(),'1')})
check('cooldown on idle connection creates no opportunistic/manual intent',()=>{const c=register();db.psql(`update public.accounting_refresh_connections set cooldown_until=clock_timestamp()+interval '5 minutes' where id=${q(c.connectionId)};`);for(const t of ['manual','opportunistic'])assert.equal(accept(c,t).outcome,'cooldown');assert.equal(count(),'0')})
check('provider-directed backoff cannot be bypassed by manual activity',()=>{const c=register();db.psql(`update public.accounting_refresh_connections set provider_not_before=clock_timestamp()+interval '1 hour' where id=${q(c.connectionId)};`);assert.equal(accept(c,'manual').outcome,'cooldown');assert.equal(count(),'0')})
check('active retry/attention/reconnect work is observed, never replaced',()=>{const c=register(),a=accept(c,'manual');for(const phase of ['retry_wait','attention_required','reconnect_required']){db.psql(`update public.accounting_refresh_jobs set phase=${q(phase)},failure_class='transient',failure_code='provider_unavailable',failed_at=clock_timestamp(),next_eligible_at=clock_timestamp()+interval '1 hour' where id=${q(a.job.id)};`);const b=accept(c,'opportunistic');assert.equal(b.job.id,a.job.id);assert.equal(b.outcome,phase);assert.equal(count(),'1')}})
check('disconnected scope cannot accept work',()=>{const c=register();db.psql(`update public.xero_connections_public set auth_state='disconnected' where user_id=${q(db.user)} and tenant_id='tenant-a';`);assert.throws(()=>accept(c,'manual'));assert.equal(count(),'0')})
check('onboarding without accounting queues durable first preparation',()=>{const c=register(),before=frozen(),a=accept(c,'onboarding');assert.equal(a.outcome,'started');assert.equal(a.job.stage,'accounting');assert.equal(frozen(),before)})
check('returning onboarding can prepare existing promoted accounting without provider retrieval',()=>{const r=accounting(),c=register(),a=accept(c,'onboarding');assert.equal(a.outcome,'preparing');assert.equal(a.job.stage,'derivatives');assert.equal(a.job.generationRunId,r.run??r.id??r.runId);assert.equal(db.psql('select count(*) from public.xero_sync_runs;'),'1')})
check('wrong owner/provider/epoch rejected; scheduled/internal triggers forbidden',()=>{const c=register();for(const changed of [{...c,ownerId:db.other},{...c,provider:'quickbooks'},{...c,epoch:'2'}])assert.throws(()=>accept(changed));for(const t of ['scheduled','internal','fake'])assert.throws(()=>accept(c,t));assert.equal(count(),'0')})
check('browser roles cannot accept, dispatch, claim, or read private refresh tables',()=>{for(const role of ['anon','authenticated']){assert.equal(db.psql(`select has_function_privilege('${role}','public.accept_product_accounting_refresh(uuid,uuid,text,text,bigint,text,text)','execute');`),'f');assert.throws(()=>db.psql(`set role ${role};select public.accept_product_accounting_refresh(${scope(register())},'manual');`));assert.equal(db.psql(`select has_table_privilege('${role}','public.accounting_refresh_jobs','select');`),'f')}})
check('dormant old accounting alone creates no work during recovery/eligibility checks',()=>{accounting('8 days');register();const before=frozen();db.rpc('select public.recover_accounting_refresh_work(25);select count(*) from public.list_accounting_refresh_work(25);');assert.equal(count(),'0');assert.equal(frozen(),before)})
check('onboarding/reconnect durably queue through cooldown without bypassing it',()=>{
 for(const trigger of ['onboarding','reconnect']){
  const c=register();db.psql(`update public.accounting_refresh_connections set cooldown_until=clock_timestamp()+interval '5 minutes',provider_not_before=clock_timestamp()+interval '10 minutes' where id=${q(c.connectionId)};`)
  const accepted=accept(c,trigger);assert.equal(accepted.outcome,trigger==='onboarding'?'started':'already_running');assert.ok(Date.parse(accepted.job.nextEligibleAt)>Date.now()+9*60000)
  assert.equal(db.rpc('select count(*) from public.list_accounting_refresh_work(25);'),'0')
 }
})
