import { invoiceFixture } from './customerFixture'
import type { DisputeWorklistRow, DisputeWorklistQuery, DisputeWorklistResponse } from '@/lib/collections/dispute-worklist'
export const disputeQuery: DisputeWorklistQuery = { status: 'active', customer: '', q: '', sort: 'amount_desc', page: 1, pageSize: 25 }
export const disputeFixture: DisputeWorklistRow = { ...invoiceFixture, disputeId: 'synthetic-dispute', revision: '4', sourceSystem: 'xero',
 customerSourceId: 'synthetic-1', customerName: 'Northbridge Supplies', contextFromPreviousSnapshot: false, overdueDays: 42,
 createdAt: '2026-10-01T10:00:00Z', resolvedAt: null, isOperationallySettled: false, grossOutstandingBase: '5000', effectiveDisputedBase: '1200', collectibleBase: '3050',
 customerHref: '/customers?tenantId=synthetic&customerSourceId=synthetic-1' }
export const disputeFixtures: DisputeWorklistRow[] = [
 { ...disputeFixture, disputeMode: 'full', currentAmountDueNative: '5000', recordedDisputedAmountNative: '5000', effectiveDisputedAmountNative: '5000', effectiveDisputedBase: '5000', activePromise: null, activePromisedCoverageAmountNative: '0', collectibleAmountNative: '0', toChaseAmountNative: '0' },
 { ...disputeFixture, disputeId: 'synthetic-partial', invoiceSourceId: 'synthetic-invoice-2', invoiceNumber: 'INV-1056', customerSourceId: 'synthetic-2', customerName: 'Cedar & Finch Studio', activePromise: null, activePromisedCoverageAmountNative: '0', collectibleAmountNative: '3800', toChaseAmountNative: '3800' },
 { ...disputeFixture, disputeId: 'synthetic-review', invoiceSourceId: 'synthetic-invoice-3', invoiceNumber: 'INV-1060', customerSourceId: 'synthetic-3', customerName: 'Harbour Engineering', needsReview: true, activePromisedCoverageAmountNative: '0', collectibleAmountNative: '0', toChaseAmountNative: '0', currentAmountDueNative: '800', recordedDisputedAmountNative: '1200', effectiveDisputedAmountNative: '800', effectiveDisputedBase: '800' },
 { ...disputeFixture, disputeId: 'synthetic-eur', invoiceSourceId: 'synthetic-invoice-4', invoiceNumber: 'INV-1070', customerName: 'Aster Services', currencyCode: 'EUR', activePromise: null, activePromisedCoverageAmountNative: '0', recordedDisputedAmountNative: '850.50', collectibleAmountNative: '4149.50', toChaseAmountNative: '4149.50', effectiveDisputedAmountNative: '850.50', effectiveDisputedBase: '750' },
 { ...disputeFixture, disputeId: 'synthetic-resolved', invoiceSourceId: 'synthetic-invoice-5', invoiceNumber: 'INV-1080', isActive: false, isResolved: true, resolvedAt: '2026-10-09T12:00:00Z', effectiveDisputedAmountNative: '0', effectiveDisputedBase: '0', collectibleAmountNative: '4250', toChaseAmountNative: '4250' },
 { ...disputeFixture, disputeId: 'synthetic-settled', invoiceSourceId: 'synthetic-invoice-6', invoiceNumber: 'INV-1090', invoiceState: 'settled', currentAmountDueNative: '0', effectiveDisputedAmountNative: '0', effectiveDisputedBase: '0', isOperationallySettled: true, activePromisedCoverageAmountNative: '0', collectibleAmountNative: '0', toChaseAmountNative: '0' },
 { ...disputeFixture, disputeId: 'synthetic-unavailable', invoiceSourceId: 'synthetic-invoice-7', invoiceNumber: 'INV-1100', invoiceState: 'unavailable', currentAmountDueNative: null, effectiveDisputedAmountNative: null, effectiveDisputedBase: null, contextFromPreviousSnapshot: true, activePromisedCoverageAmountNative: null, collectibleAmountNative: null, toChaseAmountNative: null },
]
export const disputeResponse = (rows = disputeFixtures, query = disputeQuery): DisputeWorklistResponse => ({ ok: true, tenantId: 'synthetic', organisationBaseCurrency: 'GBP', rows, query, total: rows.length, pageCount: 1,
 customers: [{ sourceId: 'synthetic-1', name: 'Northbridge Supplies' }, { sourceId: 'synthetic-2', name: 'Cedar & Finch Studio' }, { sourceId: 'synthetic-3', name: 'Harbour Engineering' }] })
